matrix:
  include:
    - language: php
      php: '5.6'
      install: composer install
      script:
        - composer ci-lint
        - composer ci-mess-detect
        - composer ci-unit-test

    - language: php
      php: '7.0'
      install: composer install
      script:
        - composer ci-lint
        - composer ci-mess-detect
        - composer ci-unit-test

    - language: php
      php: '7.1'
      install: composer install
      script:
        - composer ci-lint
        - composer ci-mess-detect
        - composer ci-unit-test

    - language: ruby
      rvm: '2.3.3'
      script:
        - bundle exec jekyll build -t -s docs -d docs/_site
        - bundle exec htmlproofer -t --log-level :warn --check-html docs/_site

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
