title: NoteScript by AJ Michels
description: A script for note taking on unix/linux based systems written in PHP.
author: AJ Michels
email: ajmichels.web@gmail.com
permalink: pretty
twitter_username: ajmichels
github_username:  ajmichels
github:
    zip_url: 'http://github.com/ajmichels/note-script/zipball/master'
    tar_url: 'http://github.com/ajmichels/note-script/tarball/master'
show_downloads: true
markdown: kramdown
theme: jekyll-theme-midnight
